#include "stm32f4xx_hal.h"              // Keil::Device:STM32Cube HAL:Common
#include "arm_math.h"                   // ARM::CMSIS:DSP

#define SIGNAL_LEN           320
#define IMPLUSE_RSP_LENGTH   29

extern void SystemClock_Config(void);

// Signals and impules response
// 1. input
extern float32_t inputSignal_f32_1kHz_15kHz[SIGNAL_LEN];
// 2. output
float32_t output_signal[IMPLUSE_RSP_LENGTH + SIGNAL_LEN];
// 3. impules response
const float32_t impules_response[IMPLUSE_RSP_LENGTH] = { // generated by Matlab
  -0.0018225230f, -0.0015879294f, +0.0000000000f, +0.0036977508f, +0.0080754303f, +0.0085302217f, -0.0000000000f, -0.0173976984f,
  -0.0341458607f, -0.0333591565f, +0.0000000000f, +0.0676308395f, +0.1522061835f, +0.2229246956f, +0.2504960933f, +0.2229246956f,
  +0.1522061835f, +0.0676308395f, +0.0000000000f, -0.0333591565f, -0.0341458607f, -0.0173976984f, -0.0000000000f, +0.0085302217f,
  +0.0080754303f, +0.0036977508f, +0.0000000000f, -0.0015879294f, -0.0018225230f
};


uint32_t freq;

// placeholder
float32_t inputSample, 
          impResSample, 
          outputSample;

// prototypes
void plot_input_signal(void);
void plot_impluse_response(void);
void convolution(float32_t *sig_src, float32_t *sig_dest, float32_t *imp_resp, uint32_t  sig_src_length, uint32_t  imp_resp_length);
void plot_output_signal(void);


int main() {

	HAL_Init();
	SystemClock_Config();
	freq = HAL_RCC_GetHCLKFreq();
	
	//
	// plot_input_signal();
	// plot_impluse_response();
	convolution(
			(float32_t*) inputSignal_f32_1kHz_15kHz,
			(float32_t*) output_signal,
			(float32_t*) impules_response,
			(uint32_t)   SIGNAL_LEN,
			(uint32_t)   IMPLUSE_RSP_LENGTH
	);
	plot_output_signal();
	
	
	while(1) {}
}



// 1.
void plot_input_signal(void) {
	
	int i, j;
	for(i = 0; i < SIGNAL_LEN; i++) {
		inputSample = inputSignal_f32_1kHz_15kHz[i];
		for(j = 0; j < 3000; j++) {}
	}
	
}

// 2.
void plot_impluse_response(void) {
	int i, j;
	for(i = 0; i < IMPLUSE_RSP_LENGTH; i++) {
		impResSample = impules_response[i];
		for(j = 0; j < 3000; j++) {}
	}
}

// 3. 
void convolution(
	float32_t *sig_src,
	float32_t *sig_dest,
	float32_t *imp_resp,
	uint32_t  sig_src_length,
	uint32_t  imp_resp_length
) {
	uint32_t i, j;
	// initailze
	memset(sig_dest, 0, (sig_src_length + imp_resp_length)*sizeof(float32_t));

	//
	for(i = 0; i < sig_src_length; i++) {
		for(j = 0; j < imp_resp_length; j++) {
			sig_dest[i + j] += (sig_src[i] * imp_resp[i]);
		}
	}
}

// 4.
void plot_output_signal(void) {
	
	int i, j;
	for(i = 0; i < (IMPLUSE_RSP_LENGTH + SIGNAL_LEN); i++) {
		outputSample = output_signal[i];
		for(j = 0; j < 3000; j++) {}
	}
	
}


////// end



void SystemTickHandler(void) {
	HAL_IncTick();
	HAL_SYSTICK_IRQHandler();
}



